USE [master]
GO
/****** Object:  Database [Notflix.DB]    Script Date: 15/05/2023 08:49:16 ******/
CREATE DATABASE [Notflix.DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Notiflix.DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Notflix.DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Notiflix.DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Notflix.DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Notflix.DB] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Notflix.DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Notflix.DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Notflix.DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Notflix.DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Notflix.DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Notflix.DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [Notflix.DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Notflix.DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Notflix.DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Notflix.DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Notflix.DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Notflix.DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Notflix.DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Notflix.DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Notflix.DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Notflix.DB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Notflix.DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Notflix.DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Notflix.DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Notflix.DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Notflix.DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Notflix.DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Notflix.DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Notflix.DB] SET RECOVERY FULL 
GO
ALTER DATABASE [Notflix.DB] SET  MULTI_USER 
GO
ALTER DATABASE [Notflix.DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Notflix.DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Notflix.DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Notflix.DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Notflix.DB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Notflix.DB', N'ON'
GO
ALTER DATABASE [Notflix.DB] SET QUERY_STORE = OFF
GO
USE [Notflix.DB]
GO
/****** Object:  Table [dbo].[Favorites]    Script Date: 15/05/2023 08:49:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Favorites](
	[FavoriteId] [int] IDENTITY(1,1) NOT NULL,
	[MovieId] [int] NULL,
	[UserId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[FavoriteId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Movies]    Script Date: 15/05/2023 08:49:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Movies](
	[Id] [int] NOT NULL,
	[Title] [varchar](50) NULL,
	[Rating] [int] NULL,
	[Category] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 15/05/2023 08:49:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](50) NULL,
	[LastName] [varchar](50) NULL,
 CONSTRAINT [PK__Users__3214EC076DC5190C] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Favorites]  WITH CHECK ADD  CONSTRAINT [FK_Favorites_Movie] FOREIGN KEY([MovieId])
REFERENCES [dbo].[Movies] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Favorites] CHECK CONSTRAINT [FK_Favorites_Movie]
GO
ALTER TABLE [dbo].[Favorites]  WITH CHECK ADD  CONSTRAINT [FK_Favorites_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
GO
ALTER TABLE [dbo].[Favorites] CHECK CONSTRAINT [FK_Favorites_User]
GO
USE [master]
GO
ALTER DATABASE [Notflix.DB] SET  READ_WRITE 
GO
